export const data = {
  IOS: [
    "Launch the Telegram app.",
    "At the bottom of the screen, click on the Contacts icon.",
    "At the top of the screen, click on the search bar.",
    "Type in the name of the bot - @lumios_bot",
    "Click on the bot name to display it in the chat.",
    "From the top-right hand corner of the chat window, select the bot’s profile image.",
    "Locate and select the “Add to Group” option below the “Send Message” option to access a list of groups to add members to.",
    "Select the group you wish to add the bot to.",
    "Click on “Yes” to confirm.",
  ],
  ANDROID: [
    "Launch the Telegram app.",
    "At the bottom of the screen, click on the Contacts icon.",
    "At the top of the screen, click on the search bar.",
    "Type in the name of the bot - @lumios_bot",
    "Click on the bot name to display it in the chat.",
    "From the top-right hand corner of the chat window, select the bot’s profile image.",
    "Locate and select the “Add to Group” option below the “Send Message” option to access a list of groups to add members to.",
    "Select the group you wish to add the bot to.",
    "Click on “Yes” to confirm",
  ],
  MAC: [
    "Navigate to the “Applications” folder to locate and launch the Telegram app.",
    "In the search text field at the top left-hand corner of the screen, enter the name of the bot - @lumios_bot",
    "Hit the return key for a list of bot search results matching your query.",
    "Click on the bot you wish to add to the group, the bot will open and display on the right.",
    "To bring up the bot’s profile, select the bot’s name from the top of the window.",
    "Towards the top-right hand corner of the window, select the “Add to Group” option.",
    "Select which Supergroup you want to add to the bot.",
    "Click “OK” to confirm.",
  ],
  WINDOWS: [
    "Navigate to the Windows menu to locate and launch the Telegram app.",
    "In the search text field at the top left-hand corner of the screen, enter the name of the bot - @lumios_bot",
    "Hit the return key for a list of bot search results matching your query.",
    "Click on the bot you wish to add to the group, the bot will open and display on the right.",
    "To bring up the bot’s profile, select the bot’s name from the top of the window.",
    "Towards the top-right hand corner of the window, select the “Add to Group” option.",
    "Select which Supergroup you want to add the bot to.",
    "Click “OK” to confirm.",
  ],
};
