export const data = [
  {name:"@olehzpr", rating: 3776},
  {name:"@ikeepcalm", rating: 3451},
  {name:"@deffkaaaaaa", rating: 2573},
  {name:"@mariauapoland", rating: 2373},
  {name:"@dskarpets", rating: 2373},
  {name:"@CabianoFaruana", rating: 2040},
  {name:"@Marshmallllows", rating: 2006},
  {name:"@cyrylocar", rating: 1925},
  {name:"@yarosirgend", rating: 1569},
  {name:"@Bohdan_MI", rating: 1278},
  {name:"@pupkakub", rating: 1265},
  {name:"@lychkoalexander", rating: 1052},
  {name:"@golova_le_silrade", rating: 1042},
  {name:"@b1dess", rating: 969},
  {name:"@kyryloloshka", rating: 969},
  {name:"@InfiniteSnake", rating: 785},
  {name:"@andremalille", rating: 573},
  {name:"@darpfnis", rating: 446},
  {name:"@DrozdyW", rating: 366},
  {name:"@wiastia", rating: 318},
  {name:"@o_o_n_n_0_0", rating: 242},
  {name:"@Gustavanenado", rating: 180},
  {name:"@ostrjul", rating: 65},
  {name:"@vova_cod", rating: 65},
  {name:"@Ro_moro", rating: 62},
  {name:"@alphashk", rating: 52},
  {name:"@brrevq", rating: 41},
  {name:"@vckplsidh", rating: 25},
  {name:"@exiade", rating: 15},
  {name:"@Artychanal", rating: 5},
  {name:"@haivop", rating: 0},
  {name:"@DDDUUUCCCKKK", rating: 0},
  {name:"@Deniaaaaa_a", rating: 0},
]

export const improvement = [
  {name:"@olehzpr", rating: 776},
  {name:"@ikeepcalm", rating: 451},
  {name:"@deffkaaaaaa", rating: 573},
  {name:"@mariauapoland", rating: 373},
  {name:"@dskarpets", rating:373},
  {name:"@CabianoFaruana", rating: 40},
  {name:"@Marshmallllows", rating: 6},
  {name:"@cyrylocar", rating: 925},
  {name:"@yarosirgend", rating: 569},
  {name:"@Bohdan_MI", rating: 278},
  {name:"@pupkakub", rating: 265},
  {name:"@lychkoalexander", rating: 52},
  {name:"@golova_le_silrade", rating: 42},
  {name:"@b1dess", rating: 69},
  {name:"@kyryloloshka", rating: -69},
  {name:"@InfiniteSnake", rating: 85},
  {name:"@andremalille", rating: 73},
  {name:"@darpfnis", rating: 446},
  {name:"@DrozdyW", rating: -66},
  {name:"@wiastia", rating: 18},
  {name:"@o_o_n_n_0_0", rating: 42},
  {name:"@Gustavanenado", rating: 180},
  {name:"@ostrjul", rating: 65},
  {name:"@vova_cod", rating: 999},
  {name:"@Ro_moro", rating: 62},
  {name:"@alphashk", rating: 52},
  {name:"@brrevq", rating: 41},
  {name:"@vckplsidh", rating: 25},
  {name:"@exiade", rating: 15},
  {name:"@Artychanal", rating: 5},
  {name:"@haivop", rating: 0},
  {name:"@DDDUUUCCCKKK", rating: 0},
  {name:"@Deniaaaaa_a", rating: 0},
]

export const messageDataHardcoded = [
  { name: "@vova_cod", value: 113 },
  { name: "@ikeepcalm", value: 103 },
  { name: "@deffkaaaaaa", value: 77 },
  { name: "@mariauapoland", value: 71 },
  { name: "@dskarpets", value: 71 },
  { name: "@CabianoFaruana", value: 61 },
  { name: "@Marshmallllows", value: 60 },
  { name: "@cyrylocar", value: 57 },
  { name: "@yarosirgend", value: 47 },
  { name: "@Bohdan_MI", value: 39 },
  { name: "@pupkakub", value: 39 },
  { name: "@lychkoalexander", value: 33 },
  { name: "@golova_le_silrade", value: 33 },
  { name: "@b1dess", value: 30 },
  { name: "@kyryloloshka", value: 30 },
  { name: "@InfiniteSnake", value: 24 },
  { name: "@andremalille", value: 17 },
  { name: "@darpfnis", value: 13 },
  { name: "@DrozdyW", value: 11 },
  { name: "@wiastia", value: 9 },
  { name: "@o_o_n_n_0_0", value: 7 },
  { name: "@Gustavanenado", value: 5 },
  { name: "@ostrjul", value: 2 },
  { name: "@olehzpr", value: 2 },
  { name: "@Ro_moro", value: 2 },
  { name: "@alphashk", value: 1 },
  { name: "@brrevq", value: 1 },
  { name: "@vckplsidh", value: 1 },
  { name: "@exiade", value: 1 },
  { name: "@Artychanal", value: 0 },
  { name: "@haivop", value: 0 },
  { name: "@DDDUUUCCCKKK", value: 0 },
  { name: "@Deniaaaaa_a", value: 0 },
];